stages:
  load_data:
    cmd: python src/stage_01_get_data.py --config=config/config.yaml
    deps:
      - src/stage_01_get_data.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv

  clean_data:
    cmd: python src/stage_02_clean_data.py --config=config/config.yaml

    deps:
    - src/stage_02_clean_data.py
    - src/utils/all_utils.py
    - config/config.yaml
    - artifacts/raw_local_dir/data.csv

    outs:
    - artifacts/null_dir/null.csv
    - artifacts/clean_data_dir/fill_values.csv

  feature_selection:
    cmd: python src/stage_03_feature.py --config=config/config.yaml

    deps:
    - src/stage_03_feature.py
    - config/config.yaml
    - src/utils/all_utils.py
    - artifacts/clean_data_dir/fill_values.csv

    outs:
    - artifacts/feature_selection_dir/after_feature_selection.csv
    - artifacts/feature_selection_dir/feature_imporatant_score.csv

  split_data:
    cmd: python src/stage_04_split_data.py --config=config/config.yaml --params=params.yaml

    deps:
    - src/stage_04_split_data.py
    - src/utils/all_utils.py
    - config/config.yaml
    - artifacts/feature_selection_dir/after_feature_selection.csv

    params:
    - base.random_state
    - base.test_size

    outs:
    - artifacts/split_data_dir/train.csv
    - artifacts/split_data_dir/test.csv

  train:
    cmd: python src/stage_05_train.py  --config=config/config.yaml --params=params.yaml

    deps:
      - src/stage_05_train.py
      - config/config.yaml
      - src/utils/all_utils.py
      - artifacts/split_data_dir/train.csv
    params:
      - train.criterion
      - train.min_samples_split
      - train.n_estimators
      - train.min_samples_leaf
      - train.max_features

    outs:
      - artifacts/model_dir/pipe.pkl

  model_test:
    cmd: python src/eval.py --config=config/config.yaml

    deps:
      - src/eval.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/model_dir/pipe.pkl

    
    metrics:
      - metrics.json:
          cache: False

plots:
  - Precision-Recall:
      x: recall
      y: precision
        roc.json
  
    
