data_source: 'C:\Users\hardi\Documents\mlops_dvc\diabetes.csv'
artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  null_dir: null_dir
  null_local_file: null.csv

  clean_data_dir: clean_data_dir
  fill_missing_value_df: fill_values.csv
  
  feature_selection_dir: feature_selection_dir
  feature_selection_score: feature_imporatant_score.csv
  after_selection_data: after_feature_selection.csv

  


