name: model-train-evalute
  on: [push]
  jobs:
    run:
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
        - uses: actions/checkout@v2
        - name: 'Train and Evaluate model'
        shell: bash
        run: |
        # Install requirements
          pip install -r requirements.txt

          # Pull data & run-cache from IBM COS and reproduce pipeline
          dvc pull --run-cache
          dvc repro

          # Report metrics
          echo "## Metrics" >> README.md
          git fetch --prune
          dvc metrics diff master --show-md >> README.md
    
    

        

