name: ci

# run the workflow on every push to main branch

on:
  push:
    branches:
      - 'main'
    
# your work flow job 
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: intsall requ
        run: pip install -r requirements.txt
      -
        name: Pull data & run-cache from IBM COS
        run: dvc pull --run-cache
      - 
        name: reproduce pipeline
        run: dvc repro
      - 
        name: Report metrics
        run: | 
          echo "## Metrics" >> README.md
          git fetch --prune
          dvc metrics diff master --show-md >> README.md
      









    

        

