name: ci

# run the workflow on every push to main branch

on:
  push:
    branches:
      - 'main'
    
# your work flow job 
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

       
      - name: train_eval
        run: |
        # Install requirements
          pip install -r requirements.txt

          # Pull data & run-cache from IBM COS and reproduce pipeline
          dvc pull --run-cache
          dvc repro

          # Report metrics
          echo "## Metrics" >> README.md
          git fetch --prune
          dvc metrics diff master --show-md >> README.md









    

        

