name: ci

# run the workflow on every push to main branch

on:
  push:
    branches:
      - 'main'
    
# your work flow job 
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: intsall requ
        run: pip install -r requirements.txt
      









    

        

